apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: commands
  name: webapi--deployment
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      namespace: commands
      name: webapi--pod
      labels:
        app: webapi
    spec:
      containers:
        - name: commands-webapi
          image: sirpeace/les-microservices.command-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8000"
          resources:
            requests:
              cpu: "0.25"
              memory: "128Mi"
            limits:
              cpu: "0.5"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: commands
  name: webapi--service
  labels:
    app: webapi
spec:
  type: ClusterIP
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
